apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dns
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'REPLACE_WITH_YOUR_REPO_URL'
    targetRevision: HEAD
    path: apps/dns
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: dns
  syncPolicy:
    automated: {} 