---
- name: Reboot system
  ansible.builtin.reboot:
    msg: "Rebooting system"
    reboot_timeout: 360000
    connect_timeout: 10

- name: Restart UFW
  community.general.ufw:
    state: reloaded

- name: Restart networking
  ansible.builtin.service:
    name: systemd-networkd
    state: restarted