# CentOS 7 with C++ development tools (vault.centos.org for EOL)
FROM centos:7

# Point yum at vault.centos.org (CentOS 7 EOL)
RUN sed -i 's/mirrorlist/#mirrorlist/g' /etc/yum.repos.d/CentOS-*.repo \
    && sed -i 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-*.repo

RUN yum groupinstall -y "Development Tools" \
    && yum install -y gcc-c++ make cmake gdb \
    && yum clean all

# Default to bash
CMD ["/bin/bash"]
