---
- name: Install AWS SSM Agent and CloudWatch Unified Agent on AlmaLinux 8
  hosts: all
  become: yes
  gather_facts: yes

  tasks:
    - name: Check if running on AlmaLinux 8
      assert:
        that:
          - ansible_distribution == "AlmaLinux"
          - ansible_distribution_major_version == "8"
        fail_msg: "This playbook is designed for AlmaLinux 8 only"
        success_msg: "AlmaLinux 8 detected, proceeding with installation"

    - name: Update system packages
      dnf:
        name: "*"
        state: latest
        update_cache: yes

    - name: Install required packages
      dnf:
        name:
          - wget
          - curl
          - unzip
        state: present

    - name: Check if SSM Agent is already installed
      stat:
        path: /usr/bin/amazon-ssm-agent
      register: ssm_agent_installed

    - name: Download SSM Agent RPM
      get_url:
        url: https://s3.amazonaws.com/ec2-downloads-windows/SSMAgent/latest/linux_amd64/amazon-ssm-agent.rpm
        dest: /tmp/amazon-ssm-agent.rpm
        mode: '0644'
      when: not ssm_agent_installed.stat.exists

    - name: Install SSM Agent
      dnf:
        name: /tmp/amazon-ssm-agent.rpm
        state: present
        disable_gpg_check: yes
      when: not ssm_agent_installed.stat.exists

    - name: Clean up SSM Agent RPM
      file:
        path: /tmp/amazon-ssm-agent.rpm
        state: absent
      when: not ssm_agent_installed.stat.exists

    - name: Enable and start SSM Agent service
      systemd:
        name: amazon-ssm-agent
        enabled: yes
        state: started
        daemon_reload: yes

    - name: Check if CloudWatch Unified Agent is already installed
      stat:
        path: /opt/aws/amazon-cloudwatch-agent/bin/amazon-cloudwatch-agent
      register: cloudwatch_agent_installed

    - name: Download CloudWatch Unified Agent RPM for RHEL/CentOS/AlmaLinux
      get_url:
        url: https://s3.amazonaws.com/amazoncloudwatch-agent/redhat/amd64/latest/amazon-cloudwatch-agent.rpm
        dest: /tmp/amazon-cloudwatch-agent.rpm
        mode: '0644'
      when: not cloudwatch_agent_installed.stat.exists

    - name: Install CloudWatch Unified Agent
      dnf:
        name: /tmp/amazon-cloudwatch-agent.rpm
        state: present
        disable_gpg_check: yes
      when: not cloudwatch_agent_installed.stat.exists

    - name: Clean up CloudWatch Agent RPM
      file:
        path: /tmp/amazon-cloudwatch-agent.rpm
        state: absent
      when: not cloudwatch_agent_installed.stat.exists

    - name: Enable and start CloudWatch Unified Agent service
      systemd:
        name: amazon-cloudwatch-agent
        enabled: yes
        state: started
        daemon_reload: yes

    - name: Verify SSM Agent is running
      systemd:
        name: amazon-ssm-agent
      register: ssm_status
      changed_when: false

    - name: Verify CloudWatch Agent is running
      systemd:
        name: amazon-cloudwatch-agent
      register: cloudwatch_status
      changed_when: false

    - name: Display service status
      debug:
        msg:
          - "SSM Agent status: {{ 'running' if ssm_status.status.ActiveState == 'active' else 'not running' }}"
          - "CloudWatch Agent status: {{ 'running' if cloudwatch_status.status.ActiveState == 'active' else 'not running' }}"

