apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- https://github.com/argoproj/argo-cd/manifests/cluster-install?ref=v2.7.9

patchesStrategicMerge:
- argocd-repo-server-deploy.yaml
- argocd-cm.yaml


patches:
- target:
    kind: ClusterRole
    name: argocd-application-controller
  patch: |
    - op: replace
      path: /rules
      value:
        - apiGroups: ["*"]
          resources: ["*"]
          verbs: ["*"]
        - nonResourceURLs: ["*"]
          verbs: ["*"] 