apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pihole
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:nwisnewski89/argocd.wisnewski.io.git
    targetRevision: main
    path: apps/pihole
  destination:
    server: https://kubernetes.default.svc
    namespace: pihole  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
