apiVersion: v1
data:
  02-custom.conf: |
    address=/pihole.local/192.168.4.241
    address=/pihole.wisnewski.io/192.168.4.241
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: pihole-custom-dnsmasq
  namespace: pihole
