apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pihole-pvc
  creationTimestamp: null
  labels:
    app: pihole
  namespace: pihole
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
volumeName: pihole-pv
