apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-dns
spec:
  acme:
    email: "wisnewski.nicholas.89@gmail.com"
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-dns-private-key
    solvers:
      - dns01:
          route53:
            region: us-east-1
            accessKeyIDSecretRef:
              name: route53-credentials-secret
              key: AWS_ACCESS_KEY_ID
            secretAccessKeySecretRef:
              name: route53-credentials-secret
              key: AWS_SECRET_ACCESS_KEY
    