---
- name: Update and upgrade apt packages
  ansible.builtin.apt:
    upgrade: yes
    update_cache: yes
    cache_valid_time: 86400

- name: Install bind
  ansible.builtin.apt:
    name: "{{ item }}"
  loop:
    - bind9
    - bind9utils
    - bind9-doc

- name: Set to use ipv4
  ansible.builtin.lineinfile:
    path: /etc/default/named
    regexp: ^OPTIONS=.*
    line: OPTIONS="-u bind -4"

- name: Restart and enable bind9
  ansible.builtin.systemd_service:
    name: bind9
    state: restarted
    enabled: true

- debug:
    var: hostvars[inventory_hostname]['dns_server_type']

- name: Configure primary dns server
  ansible.builtin.import_tasks:
    file: primary.yml
  when: hostvars[inventory_hostname]['dns_server_type'] == 'primary'

- name: Configure secondary dns server
  ansible.builtin.import_tasks:
    file: secondary.yml
  when: hostvars[inventory_hostname]['dns_server_type'] == 'secondary'

- name: Check conf
  ansible.builtin.shell:
    cmd: named-checkconf
    
- name: Check zone
  ansible.builtin.shell:
    cmd:  named-checkzone {{ dns_zone_name }} /etc/bind/zones/db.{{ dns_zone_name }}
  when: hostvars[inventory_hostname]['dns_server_type'] == 'primary'

- name: Check reverse zone
  ansible.builtin.shell:
    cmd: named-checkzone {{ network_reverse_octect }}.in-addr.arpa /etc/bind/zones/db.{{ network_octect }}
  when: hostvars[inventory_hostname]['dns_server_type'] == 'primary'

- name: Allow bind9 in firewall
  community.general.ufw:
    rule: allow
    name: Bind9

- name: Restart bind9
  ansible.builtin.systemd_service:
    name: bind9
    state: restarted



