--- 
- name: Copy named.conf.options
  ansible.builtin.template:
    src: named.conf.options.j2
    dest: /etc/bind/named.conf.options

- name: Copy named.conf.local
  ansible.builtin.template:
    src: named.conf.local.j2
    dest: /etc/bind/named.conf.local

- name: Create zones directory
  ansible.builtin.file:
    path: /etc/bind/zones
    state: directory

- name: Copy zone file
  ansible.builtin.template:
    src: db.zone.j2
    dest: /etc/bind/zones/db.{{ dns_zone_name }}

- name: Copy reverse zone file
  ansible.builtin.template:
    src: db.reverse.j2
    dest: "/etc/bind/zones/db.{{ network_octect }}"