{{- range $index, $job := .Values.jobs }}
{{- $jobName := index $job "job-name" }}
{{- $jobCommand := index $job "commands" }}
{{- $jobImage := index $job "image-override" }}
{{- if $jobName }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ $jobName | quote}}
  labels:
    "app.kubernetes.io/name": {{ index $.Values "app-name" | default "bsx-jobs" | quote }}
    "app.kubernetes.io/component": job
  annotations:
    "argocd.argoproj.io/hook": PostSync
    "argocd.argoproj.io/hook-delete-policy": BeforeHookCreation
spec:
  ttlSecondsAfterFinished: 300
  backoffLimit: 4
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: {{ $jobName | quote }}
          image: {{ $jobImage | default $.Values.image | quote }}
          command: |-
            {{- range $jobCommand }}
            - {{ . | quote}}
            {{- end }}
          envFrom:
            - secretRef:
              name: bsx-secret
          resources:
            requests:
              cpu: 250m
              memory: 512Mi 
            limits:
              cpu: 1000m
              memory: 2Gi
{{- end }}
{{- end }}
